# Generated by Django 3.2.9 on 2021-12-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_username_comment_username1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username1',
            new_name='username',
        ),
    ]
