# Generated by Django 3.2.9 on 2021-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_username1_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.TextField(choices=[('Fin de la pobreza', 'Fin de la pobreza'), ('Hambre Cero', 'Hambre Cero'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Educacion de Calidad', 'Educacion de Calidad'), ('Igualdad de Genero', 'Igualdad de Genero'), ('Agua Limpia y Saneamiento', 'Agua Limpia y Saneamiento'), ('Energia Asequible y no Contaminante', 'Energia Asequible y no Contaminante'), ('Trabajo Decente y Crecimiento Economico', 'Trabajo Decente y Crecimiento Economico'), ('Agua, Industria, Innovacion e Infraestructura', 'Agua, Industria, Innovacion e Infraestructura'), ('Reduccion de las Desigualdades', 'Reduccion de las Desigualdades'), ('Ciudades y Comunidades Sostenibles', 'Ciudades y Comunidades Sostenibles'), ('Produccion y Consumos Responsables', 'Produccion y Consumos Responsables'), ('Accion por el Clima', 'Accion por el Clima'), ('Vida Submarina', 'Vida Submarina'), ('Vida de Ecosistemas Terrestres', 'Vida de Ecosistemas Terrestres'), ('Paz, Justicia e Instituciones Solidas', 'Paz, Justicia e Instituciones Solidas'), ('Alianzas para lograr los objetivos', 'Alianzas para lograr los objetivos')], default='Fin de la pobreza', max_length=60),
        ),
    ]
